In [103]:
import numpy as np

In [104]:
N = 10
D = 5
mu = np.random.rand(N, 1)

In [118]:
mu.shape

(10, 1)

In [106]:
X = np.tile(mu,  D) + 0.01*np.random.randn(N, D)

In [107]:
yy = mu + 0.1*np.random.randn(N,1)

In [108]:
yy

array([[-0.03707708],
       [ 0.76168091],
       [ 0.07321083],
       [ 0.78700874],
       [ 0.03851095],
       [ 0.98279704],
       [ 0.99480649],
       [ 0.53249316],
       [ 0.43311187],
       [ 0.2044777 ]])

In [109]:
w_fit = np.linalg.lstsq(X, yy)[0]


/Users/stathis/anaconda3/envs/mlpr/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [110]:
X

array([[-0.00100583, -0.0038645 ,  0.01471907,  0.01278415, -0.01599315],
       [ 0.82338479,  0.80593344,  0.82142759,  0.80406128,  0.79640659],
       [ 0.21529474,  0.19399986,  0.1989811 ,  0.19730747,  0.21307252],
       [ 0.78268778,  0.77996089,  0.77147121,  0.78782065,  0.79018983],
       [ 0.0048578 ,  0.01982628,  0.01644526,  0.02118201,  0.02319237],
       [ 0.78689321,  0.76378892,  0.758946  ,  0.7782952 ,  0.79022292],
       [ 0.94130979,  0.92652798,  0.91838645,  0.92542831,  0.91684177],
       [ 0.49262834,  0.48247419,  0.49886801,  0.50010415,  0.50585071],
       [ 0.47880251,  0.4452168 ,  0.4673387 ,  0.45740879,  0.46007707],
       [ 0.10132773,  0.09441814,  0.10100736,  0.09619209,  0.08896423]])

In [111]:
yy

array([[-0.03707708],
       [ 0.76168091],
       [ 0.07321083],
       [ 0.78700874],
       [ 0.03851095],
       [ 0.98279704],
       [ 0.99480649],
       [ 0.53249316],
       [ 0.43311187],
       [ 0.2044777 ]])

In [112]:
w_fit

array([[ 1.13613156],
       [-0.15306144],
       [-5.24190707],
       [ 6.36176145],
       [-1.08842579]])

In [117]:
np.mean(w_fit)

0.202899740843204

In [113]:
np.matmul(X, w_fit)

array([[0.02102982],
       [0.75468559],
       [0.19517822],
       [0.87773799],
       [0.02579166],
       [0.89001257],
       [1.00297952],
       [0.50178498],
       [0.43525693],
       [0.08631885]])

In [114]:
np.mean(X)

0.4570292517664114

In [115]:
w_fit2 = np.ones([5,1 ])/5

In [116]:
np.matmul(X, w_fit2)

array([[0.00132795],
       [0.81024274],
       [0.20373114],
       [0.78242607],
       [0.01710074],
       [0.77562925],
       [0.92569886],
       [0.49598508],
       [0.46176877],
       [0.09638191]])