In [69]:
import numpy as np

In [70]:
x = np.abs(np.random.randn(10,2))
x

array([[0.76933707, 0.7332922 ],
       [0.1143621 , 1.06582266],
       [1.36063156, 0.06519352],
       [0.13019733, 0.53050571],
       [0.51490817, 0.68636522],
       [0.29479597, 0.49015479],
       [1.36639638, 1.01987115],
       [0.67254533, 0.19376172],
       [0.1324219 , 0.8015847 ],
       [0.84977103, 0.27628893]])

In [71]:
y = 2*x[:,0] + x[:,1]
y

array([2.27196634, 1.29454687, 2.78645664, 0.79090038, 1.71618157,
       1.07974673, 3.75266391, 1.53885238, 1.0664285 , 1.97583099])

In [72]:
np.log(y)

array([ 0.82064569,  0.25816072,  1.02477077, -0.23458327,  0.5401018 ,
        0.07672651,  1.32246596,  0.43103693,  0.06431522,  0.68098906])

In [87]:
np.linalg.lstsq(x,y)

/Users/stathis/anaconda3/envs/mlpr/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([2., 1.]), array([1.23065308e-30]), 2, array([2.90854429, 1.37547114]))

In [92]:
ls = np.linalg.lstsq(x,np.log(y))
l = ls[0]
l

/Users/stathis/anaconda3/envs/mlpr/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([0.81733096, 0.0624059 ])

In [85]:
# xt = x[0,:]
yh = l[0]*x[:,0] + ls[1]*x[:,1]
yh

array([0.82687353, 0.38136246, 1.1296958 , 0.24970991, 0.60624541,
       0.37334223, 1.39227681, 0.60202935, 0.32474963, 0.76917294])

In [86]:
np.exp(yh)

array([2.28615995, 1.46427825, 3.09471494, 1.28365299, 1.83353429,
       1.45258138, 4.0240015 , 1.82582028, 1.38368416, 2.15798073])

In [84]:
y

array([2.27196634, 1.29454687, 2.78645664, 0.79090038, 1.71618157,
       1.07974673, 3.75266391, 1.53885238, 1.0664285 , 1.97583099])